---
title: "K"
output: 
  html_document: 
    df_print: kable
    theme: readable
---

```{r, include=FALSE}
GROUPS = scan(text = grep("GROUPS = ", readLines('global.make'), value = TRUE), what = 'character')[-(1:2)]
```

* Imputation process summary [[html]](imputation-process.html)
* Baseline characteristics: `r sprintf("[%s](table-baseline-characteristics_%s.html)", GROUPS, GROUPS)`
* Incidences: `r sprintf("[%s](table-incidences_%s.html)", GROUPS, GROUPS)`
* Cumulative incidences: `r sprintf("[%s](figure-cumulative-incidences_%s.html)", GROUPS, GROUPS)`
* Unadjusted hazard ratios: `r sprintf("[%s](table-hazard-ratios_%s.html)", GROUPS, GROUPS)`
    * Hazard ratios adjusted by regicor variables: `r sprintf("[%s](table-hazard-ratios-01_%s.html)", GROUPS, GROUPS)`
    * Hazard ratios adjusted by variables selected using forward-backward based on BIC criterion: `r sprintf("[%s](table-hazard-ratios-03_%s.html)", GROUPS, GROUPS)`
    * Hazard ratios __using 3 categories__ adjusted by variables selected using forward-backward based on BIC criterion:  `r sprintf("[%s](table-hazard-ratios-03-3_categories_%s.html)", GROUPS, GROUPS)`
* Hazard ratios forest plots: `r sprintf("[%s](figure-hazard-ratios_%s.html)", GROUPS, GROUPS)`

* Smoothened hazard ratios: `r sprintf("[%s](figure-smoothened-hazard-ratios_%s.html)", GROUPS, GROUPS)`
    * Reference at ABI=1.2:  `r sprintf("[%s](figure-smoothened-hazard-ratios_12_%s.html)", GROUPS, GROUPS)`

## Figures & Tables


* __Table 01__. <br/>Characteristics of the study population [[docx]](table01.docx)
    * (a) Characteristics of the study population with diabetes [[docx]](table01a.docx)
    * (b) Characteristics of the study population without diabetes [[docx]](table01b.docx)
* __Supplementary Table 01__. <br/>Missing percentage and comparison of the characteristics of the imputed data with the complete-case population [[docx]](sup-table01.docx)
* __Supplementary Table 02__. <br/>Characteristics of the study population. Complete cases [[docx]](sup-table02.docx)
    * (a) Characteristics of the study population with diabetes. Complete cases [[docx]](sup-table02a.docx)
    * (b) Characteristics of the study population without diabetes. Complete cases [[docx]](sup-table02b.docx)
* __Supplementary Table 03__. <br/>Unadjusted and adjusted hazard ratios for haemorragic stroke by ABI category [[docx]](sup-table03.docx)
    * (a) Unadjusted and adjusted hazard ratios for haemorragic stroke by diabetic condition and ABI category [[docx]](sup-table03a.docx)
* __Supplementary Table 04__. <br/>Unadjusted and adjusted hazard ratios for haemorragic stroke by ABI category. Complete cases [[docx]](sup-table04.docx)
    * (a) Unadjusted and adjusted hazard ratios for haemorragic stroke by diabetic condition and ABI category. Complete cases [[docx]](sup-table04a.docx)


* Flow-chart [[svg]](flow-chart.svg) [[pdf]](flow-chart.pdf)
* Figure 1. Hazard ratios for haemorrhagic stroke by ABI in persons with and without diabetes [[svg]](figure01.svg) [[pdf]](figure01.pdf)
* Supplementary Figure 1. Hazard ratios for haemorrhagic stroke by ABI in persons with and without diabetes. Complete cases [[svg]](sup-figure01.svg) [[pdf]](sup-figure01.pdf)


<!--
    * Hazard ratios adjusted by variables selected using forward-backward based on AIC criterion [[html]](table-hazard-ratios-02.html)

    * Hazard ratios __with people aged below 60__ adjusted by variables selected using forward-backward based on BIC criterion [[html]](table-hazard-ratios-03-age_lower_60.html)
    * Hazard ratios __with people aged below 75__ adjusted by variables selected using forward-backward based on BIC criterion [[html]](table-hazard-ratios-03-age_lower_75.html)
    * Hazard ratios __with non-smoking people__ adjusted by variables selected using forward-backward based on BIC criterion [[html]](table-hazard-ratios-03-non-smokers.html)
    * Hazard ratios __category for people with itb=0.9 modified__ adjusted by variables selected using forward-backward based on BIC criterion [[html]](table-hazard-ratios-03-0.9_category.html)
    * Hazard ratios __by cv-risk categories__ adjusted by variables selected using forward-backward based on BIC criterion:
         * 0 ≤ regicor ≤ 5: [[html]](table-hazard-ratios-03-regicor_0-5.html) 
         * 0 ≤ regicor ≤ 10: [[html]](table-hazard-ratios-03-regicor_0-10.html) 
         * 5 < regicor ≤ 10: [[html]](table-hazard-ratios-03-regicor_5-10.html)
         * 10 < regicor: [[html]](table-hazard-ratios-03-regicor_10p.html)
    * Hazard ratios forest plot [[html]](figure-hazard-ratios.html)
* Figures of smoothened hazard-ratios [[html]](smoothened-hazard-ratios.html)

* __Final Figures&Tables__:
    * Table 1. Descriptives [[docx]](table_01.docx)
    * Table 2. Incidences [[docx]](table_02.docx)
    * Figure 1. Flow chart [[svg]](flow-chart.svg) [[pdf]](flow-chart.pdf)
    * Figure 2. Adjusted hazard ratios [[svg]](figure02.svg) [[pdf]](figure02.pdf)
    * Table 1 (Supplementary). Descriptives [[docx]](table_01_sup.docx)
    * Table 2 (Supplementary). Descriptives (Complete-case) [[docx]](table_02_sup.docx)
    * Table 3 (Supplementary). Incidences (Complete-case) [[docx]](table_03_sup.docx)
    * Figure 1 (Supplementary). Hazard ratios (Complete-case) [[svg]](figure01_sup.svg) [[pdf]](figure01_sup.pdf)
    * Figure 2 (Supplementary). Unadjusted hazard ratios [[svg]](figure02_sup.svg) [[pdf]](figure02_sup.pdf)

* __Alternative Figures&Tables__:
    * Figure 2. Adjusted hazard ratios. Version 1: [[svg]](figure02_alt1.svg) [[pdf]](figure02_alt1.pdf) Version2:  [[svg]](figure02_alt2.svg) [[pdf]](figure02_alt2.pdf) 
-->
