---
title: "Cumulative incidences for `r GROUP` group"
output: 
  html_document: 
    df_print: kable
    toc: yes
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(ggplot2)
library(ggthemes)
theme_set(theme_stata())
load(sprintf('cumulative-incidences_%s.RData', GROUP))
source('../R/geom-stepribbon.r')
knitr::opts_chunk$set(echo = FALSE)
OUTCOMES = unique(global.mi$variable)
```

# Results for all population

## Multiple-imputed descriptives

```{r, fig.width=6.5, heighth = 5.5, out.width='100%'}
for(outcome in OUTCOMES){
  dplot = global.mi %>%
    mutate(strata = gsub('itb_cat=', '', strata)) %>%
    filter(variable == outcome)
  p = ggplot(data = dplot) +
    geom_stepribbon(aes(x = time, ymin = 1-conf.low, ymax = 1-conf.high, fill = strata), col = NA, alpha = 0.15) + 
    geom_step(aes(x = time, y = 1-estimate, col = strata)) +
    labs(title = sprintf('Outcome %s', outcome), x = 'Time', y = 'Cumulative incidence', fill = 'ABI \ncategories', col = 'ABI \ncategories')
  print(p)
}
```

## Complete-case descriptives

```{r, fig.width=6.5, heighth = 5.5, out.width='100%'}
for(outcome in OUTCOMES){
  dplot = global.cc %>%
    mutate(strata = gsub('itb_cat=', '', strata)) %>%
    filter(variable == outcome)
  p = ggplot(data = dplot) +
    geom_stepribbon(aes(x = time, ymin = 1-conf.low, ymax = 1-conf.high, fill = strata), col = NA, alpha = 0.15) + 
    geom_step(aes(x = time, y = 1-estimate, col = strata))
  print(p)
}
```
