---
title: "Hazard ratios for `r GROUP` group"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    df_print: kable
    toc: yes
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(ggplot2)
library(ggthemes)
theme_set(theme_stata())
load(sprintf('hazard-ratios_%s.RData', GROUP))
source('../R/geom-stepribbon.r')
knitr::opts_chunk$set(echo = FALSE)
METHODS = names(HRs.mi)
```

# Summary

```{r, fig.width=8.8, fig.height=6, warning=FALSE}
dplot = bind_rows(lapply(HRs.mi, first), .id = 'method') %>%
  filter(substr(rowname, 1, 7) == 'itb_cat') %>%
  transmute(
    method = factor(method, levels = METHODS),
    outcome = variable,
    abi = gsub('itb_cat', '', rowname),
    haz = exp(estimate),
    lo = exp(estimate - 1.96 * std.error),
    hi = exp(estimate + 1.96 * std.error)
  )
ggplot(data = dplot) +
  geom_hline(yintercept = 1, col = 'red', linetype = 2) +
  geom_errorbar(aes(x = abi, ymin = lo, ymax = hi, col=method), position =  position_dodge(width=0.7), width = 0.2) +
  geom_point(aes(x = abi, y = haz, col = method), shape = 18, size = 2, position =  position_dodge(width=0.7)) +
  facet_wrap(~outcome, nrow  = 1) +
  theme(
    axis.text.y = element_text(angle = 0)
  ) +
  labs(y = 'Hazard ratios', x = 'ABI category') +
  coord_flip(ylim = c(0,5))
```


# Multiple imputation

## Unadjusted

```{r}
mi = HRs.mi$Unadjusted$global
```

```{r, ref.label='mi_figure', fig.width=6.6, fig.height=5}
```

## Regicor variables

```{r}
mi = HRs.mi$`Regicor variables`$global
```

```{r, ref.label='mi_figure', fig.width=6.6, fig.height=5}
```

```{r, ref.label='mi_adjusting', results='asis', warning=FALSE}
```

## BIC criterion

```{r}
mi = HRs.mi$`BIC criterion`$global
```

```{r, ref.label='mi_figure', fig.width=6.6, fig.height=5}
```

```{r, ref.label='mi_adjusting', results='asis', warning=FALSE}
```


# Complete-case

## Unadjusted

```{r}
cc = HRs.cc$Unadjusted$global
```

```{r, ref.label='cc_figure'}
```

## Regicor variables

```{r}
cc = HRs.cc$`Regicor variables`$global
```

```{r, ref.label='cc_figure', fig.width=6.6, fig.height=5}
```

```{r, ref.label='cc_adjusting', results='asis', warning=FALSE}
```

## BIC criterion

```{r}
cc = HRs.cc$`BIC criterion`$global
```

```{r, ref.label='cc_figure', fig.width=6.6, fig.height=5}
```

```{r, ref.label='cc_adjusting', results='asis', warning=FALSE}
```


************

```{r mi_figure, eval=FALSE}
dplot = mi %>%
  filter(substr(rowname, 1, 7) == 'itb_cat') %>%
  transmute(
    outcome = variable,
    abi = gsub('itb_cat', '', rowname),
    haz = exp(estimate),
    lo = exp(estimate - 1.96 * std.error),
    hi = exp(estimate + 1.96 * std.error)
  )
ggplot(data = dplot) +
  geom_vline(xintercept = 1, col = 'red', linetype = 2) +
  geom_errorbarh(aes(y = abi, xmin = lo, xmax = hi), height = 0.4) +
  geom_point(aes(y = abi, x = haz), shape = 18, size = 2) +
  facet_wrap(~outcome, ncol = 2) +
  theme(
    axis.text.y = element_text(angle = 0)
  ) +
  labs(x = 'Hazard ratios', y = 'ABI category')
```

```{r mi_adjusting, eval=FALSE}
adj = mi %>%
  filter(substr(rowname, 1, 7) != 'itb_cat') %>%
  group_by(variable) %>%
  summarise(`adjusting variables` = paste(rowname, collapse = '+'))
for(i in 1:nrow(adj)){
  cat(sprintf("* __%s__: %s\n", adj$variable[i], adj$`adjusting variables`[i]))
}
```

```{r cc_figure, eval=FALSE}
dplot = cc %>%
  filter(substr(term, 1, 7) == 'itb_cat') %>%
  transmute(
    outcome = variable,
    abi = gsub('itb_cat', '', term),
    haz = exp(estimate),
    lo = exp(estimate - 1.96 * std.error),
    hi = exp(estimate + 1.96 * std.error)
  )
ggplot(data = dplot) +
  geom_vline(xintercept = 1, col = 'red', linetype = 2) +
  geom_errorbarh(aes(y = abi, xmin = lo, xmax = hi), height = 0.4) +
  geom_point(aes(y = abi, x = haz), shape = 18, size = 2) +
  facet_wrap(~outcome, ncol = 2) +
  theme(
    axis.text.y = element_text(angle = 0)
  ) +
  labs(x = 'Hazard ratios', y = 'ABI category')
```

```{r cc_adjusting, eval=FALSE}
adj = cc %>%
  filter(substr(term, 1, 7) != 'itb_cat') %>%
  group_by(variable) %>%
  summarise(`adjusting variables` = paste(term, collapse = '+'))
for(i in 1:nrow(adj)){
  cat(sprintf("* __%s__: %s\n", adj$variable[i], adj$`adjusting variables`[i]))
}
```

