---
title: "Hazard ratios adjusted by regicor variable for `r GROUP` group"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    df_print: kable
    toc: yes
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
load(sprintf('hazard-ratios-01_%s.RData', GROUP))
knitr::opts_chunk$set(echo = FALSE)
```

# Results for all population

## Multiple-imputed descriptives

```{r}
global.mi %>%
  mutate(haz = exp(estimate),
         lo = exp(estimate - 1.96 * std.error),
         hi = exp(estimate + 1.96 * std.error),
         term = gsub('itb_cat', '', rowname)) %>%
  select(outcome = variable, term, haz, lo, hi, p.value, fmi)
```

## Complete-case descriptives

```{r}
global.cc %>%
  mutate(haz = exp(estimate),
         lo = exp(estimate - 1.96 * std.error),
         hi = exp(estimate + 1.96 * std.error),
         term = gsub('itb_cat', '', term)) %>%
  select(outcome = variable, term, haz, lo, hi, p.value)
```

# Results by sex

## Multiple-imputed descriptives

```{r}
sex.mi %>%
  mutate(haz = exp(estimate),
         lo = exp(estimate - 1.96 * std.error),
         hi = exp(estimate + 1.96 * std.error),
         term = gsub('itb_cat', '', rowname)) %>%
  select(outcome = variable, sex, term, haz, lo, hi, p.value, fmi)
```

## Complete-case descriptives

```{r}
sex.cc %>%
  mutate(haz = exp(estimate),
         lo = exp(estimate - 1.96 * std.error),
         hi = exp(estimate + 1.96 * std.error),
         term = gsub('itb_cat', '', term)) %>%
  select(outcome = variable, sex, term, haz, lo, hi, p.value)
```
